seed: -1

preprocess:
  filter_T:
    - ticker_timer
    - ltrim_vacant
  project: to_hourly
  filter_V:
    - remove_outlier
    - fill_nan
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  split: 0.2
  inlen: 72
  outlen: 1            # must be 1 for clf
  encoder:
    name: ex_thresh_24h
    params:
      thresh: 1

model:
  name: XGBoost_clf
  params:
    model: XGBClassifier
    objective: multi:softprob
    # no GridSearchCV, no 'gs_param'
    param:
      max_depth: 5
      n_estimators: 30
      learning_rate: 0.1
