seed: -1

preprocess:
  filter_T:
    - ticker_timer
    - ltrim_vacant
  project: to_hourly
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  split: 0.2
  in: 24
  out: 1            # must be 1 for clf
  encoder:
    name: ex_thresh_3h
    params:
      thresh: 1.5

model:
  name: XGBoost_clf
  params:
    model: XGBClassifier
    objective: 'multi:softprob'
    gs_params:
      param_grid:
        max_depth: [3, 5]
        n_estimators: [20]
        learning_rate: [0.1, 0.15]
      cv: 5
      verbose: 2
      n_jobs: -1
      scoring: accuracy
