seed: -1

preprocess:
  filter_T:
    - ticker_timer
    - ltrim_vacant
  project: to_hourly
  filter_V:
    - remove_outlier
    - fill_nan
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  split: 0.2
  inlen: 72
  outlen: 1            # must be 1 for clf
  encoder:
    name: ex_thresh_3h
    params:
      thresh: 1.5

model:
  name: CRNN_clf
  params:
    rnn_type: LSTM
    rnn_in: 1         # := n_feature
    rnn_out: 4        # := num_class
    rnn_hidden: 32
    rnn_layers: 1
    epochs: 30
    batch_size: 32
    optimizer: Adam
    lr: 1e-3
    weight_decay: 1e-5
    loss: cross_entropy
