misc:
  name: XGBoost
  seed: 114514
#  target: all
#  target: data
#  target: train
#  target: eval
  target: infer

data:
  - data/w21003.csv

preprocess:
#  - to_daily
  - to_hourly
#  - yichang
#  - walvent
  - log

dataset:
  train: 10000
  eval: 1000
  in: 128
  out: 24

model:
  arch: XGBoost_rgr
  params:
    param_grid:
      max_depth: [3, 4, 5, 6, 7]
      n_estimators: [20, 25, 30, 35, 50]
      learning_rate: [0.1, 0.12, 0.125, 0.13, 0.15]
    cv: 5
    verbose: 2
    n_jobs: -1
    scoring: 'neg_median_absolute_error'
  
train:
  kfold: 0
