misc:
  name: GRU2_rgr
  seed: 114514
  target:
    - all

data:
  - data/w21003.csv

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_hourly
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  train: 9000
  eval: 1000
  in: 96
  out: 6

model:
  name: CRNN_rgr
  config:
    rnn_type: GRU
    rnn_in: 1
    rnn_out: 6        # := dataset.out
    rnn_hidden: 32
    rnn_layers: 2
    rnn_dropout: 0.5
    epochs: 30
    batch_size: 32
    optimizer: Adam
    lr: 1e-3
    weight_decay: 1e-5
    loss: mse_loss
