misc:
  name: GRU_clf_3h
  seed: 114514
  target:
    - all

data:
  - data/w21003.csv

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_hourly
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  method: split
  split_ratio: 0.2
  in: 72
  out: 1            # must be 1 for clf
  encode:
    name: ex_thresh_3h
    params:
      thresh: 1.5

model:
  name: CRNN_clf
  config:
    rnn_type: GRU
    rnn_in: 1
    rnn_out: 4        # := num_class
    rnn_hidden: 32
    rnn_layers: 1
    epochs: 30
    batch_size: 32
    optimizer: Adam
    lr: 1e-3
    weight_decay: 1e-5
    loss: cross_entropy
