misc:
  name: GRU_rgr
  seed: 114514
  target:
    - all

data:
  - data/w21003.csv

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_hourly
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  train: 10000
  eval: 1000
  in: 96
  out: 6

model:
  name: RNN_rgr
  config:
    model: GRU
    d_in: 1
    d_out: 6        # := dataset.out
    d_hidden: 32
    n_layers: 1
    epochs: 30
    batch_size: 32
    optimizer: Adam
    lr: 1e-3
    weight_decay: 1e-5
    loss: mse_loss
