misc:
  name: LSTM_clf_3h
  seed: 114514
  target:
    - all

data:
  - data/w21003.csv

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_hourly
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  train: 10000
  eval: 1000
  in: 72
  out: 1            # := 1, fixed
  encode:
    name: ex_thresh_3h
    params:
      thresh: 1.5

model:
  name: LSTM_rgr
  config:
    model: LSTM
    d_in: 1
    d_out: 4        # := num_class
    d_hidden: 128
    n_layers: 1
    epochs: 30
    batch_size: 32
    optimizer: Adam
    lr: 1e-3
    weight_decay: 1e-5
    loss: cross_entropy
