seed: -1

preprocess:
  filter_T:
    - ticker_timer
    - ltrim_vacant
  project: to_daily
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  split: 0.2
  inlen: 31
  outlen: 7

model:
  name: XGBoost_rgr
  params:
    model: XGBRegressor
    objective: reg:squarederror
    gs_params:
      param_grid:
        max_depth: [3, 5]
        n_estimators: [20]
        learning_rate: [0.1, 0.15]
      cv: 5
      verbose: 2
      n_jobs: -1
      scoring: neg_median_absolute_error
