seed: -1

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_hourly
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  split: 0.2
  in: 96
  out: 6

model:
  name: CRNN_rgr
  params:
    rnn_type: LSTM
    rnn_in: 1
    rnn_out: 6        # := dataset.out
    rnn_hidden: 32
    rnn_layers: 1
    epochs: 30
    batch_size: 32
    optimizer: Adam
    lr: 1e-3
    weight_decay: 1e-5
    loss: mse_loss
