misc:
  name: XGBoost_clf_24h
  seed: 114514
  target:
    - all

data:
  - data/w21003.csv

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_hourly
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  train: 10000
  eval: 1000
  in: 72
  out: 1            # must be 1 for clf
  encode:
    name: ex_thresh_24h
    params:
      thresh: 1.5

model:
  name: XGBoost_clf
  config:
    model: XGBClassifier
    objective: 'multi:softprob'
    gs_params:
      param_grid:
        max_depth: [3, 5]
        n_estimators: [20]
        learning_rate: [0.1, 0.15]
      cv: 5
      verbose: 2
      n_jobs: -1
      scoring: accuracy
