misc:
  name: XGBoost_rgr_d
  seed: 114514
  target:
    - all

data:
  - data/w21003.csv

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_daily
  filter_V:
    - remove_outlier
    - wavlet_transform
  transform:
    - minmax_norm

dataset:
  train: 9000
  eval: 1000
  in: 31
  out: 7

model:
  name: XGBoost_rgr
  config:
    model: XGBRegressor
    objective: 'reg:squarederror'
    gs_params:
      param_grid:
        max_depth: [3, 5]
        n_estimators: [20]
        learning_rate: [0.1, 0.15]
      cv: 5
      verbose: 2
      n_jobs: -1
      scoring: neg_median_absolute_error
