misc:
  name: XGBoost_rgr
  seed: 114514
  target:
    - all
#    - data
#　  - train
#　  - eval

data:
  - data/w21003.csv

preprocess:
  filter_T:
    - ltrim_vacant
  project:
    - to_hourly
#    - to_daily
  filter_V:
#    - yichang
#    - walvent

dataset:
  train: 10000
  eval: 1000
  in: 128
  out: 24

dataloader:
  transform:
    - log

model:
  arch: XGBoost_rgr
  params:
    param_grid:
      max_depth: [3, 5]
      n_estimators: [20]
      learning_rate: [0.1, 0.15]
    cv: 5
    verbose: 2
    n_jobs: -1
    scoring: 'neg_median_absolute_error'
